export default {
	API_URL: process.env.API_URL,

	CDN_API_ENDPOINT: process.env.CDN_API_ENDPOINT,
	CDN_API_KEY: process.env.CDN_API_KEY,
	CDN_API_SECRET: process.env.CDN_API_SECRET,
	CDN_API_IMAGES_ROUTE: process.env.CDN_API_IMAGES_ROUTE,
	CDN_API_IMAGES_DELETE_ROUTE: process.env.CDN_API_IMAGES_DELETE_ROUTE,

	CDN_API_PROFILE_IMAGES_PRESET: process.env.CDN_API_PROFILE_IMAGES_PRESET,
	CDN_API_PROJECT_IMAGES_PRESET: process.env.CDN_API_PROJECT_IMAGES_PRESET,

	CDN_ENDPOINT: process.env.CDN_ENDPOINT,
	CDN_IMAGES_ROUTE: process.env.CDN_IMAGES_ROUTE,
}
