FROM node:stretch

RUN npm install pg
RUN npm install dotenv
RUN npm install hashids
RUN npm install express
RUN npm install graphql
RUN npm install base64url
RUN npm install body-parser
RUN npm install postgraphile-core
RUN npm install @graphile-contrib/pg-simplify-inflector

# sudo docker build -f Dockerfile-postgraphile-node -t postgraphile .
