FROM postgres:10-alpine

RUN apk update \
	&& apk add --no-cache alpine-sdk postgresql-dev=10.5-r0 \
	&& git clone https://github.com/iCyberon/pg_hashids.git \
	&& cd pg_hashids \
	&& make; make install \
	&& cd .. \
	&& rm -rf pg_hashids \
	&& git clone https://github.com/blainehansen/ap_pgutils.git  \
	&& cd ap_pgutils \
	&& make; make install \
	&& cd .. \
	&& rm -rf ap_pgutils \
	&& apk del alpine-sdk postgresql-dev

# sudo docker build -f Dockerfile-postgres-custom -t postgres-custom .
