version: '3'
services:
  launch-go-api:
    image: go-anywhere
    links:
      - launch-database
    ports:
      - "5050:5050"
    volumes:
      - .env.launch.dev.sh:/config/.env
      - ./launch/go:/go/src/main
    working_dir: /go/src/main
    command: reflex -g '*.go' -G '*_test.go' --start-service=true -- sh -c "go run -tags=jsoniter *.go"
    tty: true

  launch-database:
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=dev_database
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=asdf
    ports:
      - "5432:5432"
    volumes:
      - ./launch/initdb:/docker-entrypoint-initdb.d/
    command: postgres -c 'max_wal_size=2GB'
