version: '3'
services:
  database:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_DB=dev_database
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=asdf
    container_name: database
    ports:
      - "5432:5432"
    # volumes:
    #   - ./server:/server
    command: postgres -c 'max_wal_size=2GB'
