version: '3'
services:
  # go-api:
  #   image: go-anywhere:latest
  #   container_name: go-api
  #   links:
  #     - go-database
  #   ports:
  #     - "5050:5050"
  #   tty: true
  #   volumes:
  #     - ./server:/go/src/main
  #     - ./server-bin:/go/bin
  #   working_dir: /go/src/main
  #   command: reflex -g '*.go' -G '*_test.go' --start-service=true -- sh -c "kallax gen && go run -tags=jsoniter *.go"
  go-database:
    image: postgres-custom
    environment:
      - POSTGRES_DB=dev_database
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=asdf
    container_name: go-database
    ports:
      - "5432:5432"
    # volumes:
    #   - ./server:/server
    command: postgres -c 'max_wal_size=2GB'
