FROM postgres:10-alpine

RUN apk update \
	&& apk add --no-cache alpine-sdk postgresql-dev=10.4-r0 \
	&& git clone https://github.com/iCyberon/pg_hashids.git \
	&& cd pg_hashids \
	&& make; make install \
	&& cd .. \
	&& rm -rf pg_hashids \
	&& apk del alpine-sdk postgresql-dev
