source .env.dev.sh

PGPASSWORD=$ADMIN_DATABASE_PASSWORD psql -U $ADMIN_DATABASE_USER -h $SYSTEM_DATABASE_HOST $DATABASE_DB_NAME -f data-schema/setup.sql
PGPASSWORD=$ADMIN_DATABASE_PASSWORD psql -U $ADMIN_DATABASE_USER -h $SYSTEM_DATABASE_HOST $DATABASE_DB_NAME -f data-schema/person.sql
PGPASSWORD=$ADMIN_DATABASE_PASSWORD psql -U $ADMIN_DATABASE_USER -h $SYSTEM_DATABASE_HOST $DATABASE_DB_NAME -f data-schema/project.sql

PGPASSWORD=$ADMIN_DATABASE_PASSWORD psql -U $ADMIN_DATABASE_USER -h $SYSTEM_DATABASE_HOST $DATABASE_DB_NAME -f data-schema/fixtures.sql
