insert into users (name, bio, email, password) values
	('Abraham Camacho', 'She did not cheat on the test, for it was not the right thing to do.', 'abraham@gmail.com', 'password'::bytea),
	('Terrell Finley', 'I would have gotten the promotion, but my attendance wasnt good enough.', 'terrell@gmail.com', 'password'::bytea),
	('Quinn Chaney', 'What was the person thinking when they discovered cows milk was fine for human consumption and why did they do it in the first place!?', 'quinn@gmail.com', 'password'::bytea),
	('Jerome Shields', 'Sometimes it is better to just walk away from things and go back to them later when youre in a better frame of mind.', 'jerome@gmail.com', 'password'::bytea),
	('Val Cuevas', 'The shooter says goodbye to his love.', 'val@gmail.com', 'password'::bytea),
	('Myles Werner', 'If Purple People Eaters are real where do they find purple people to eat?', 'myles@gmail.com', 'password'::bytea),
	('Christopher Roy', 'Dont step on the broken glass.', 'christopher@gmail.com', 'password'::bytea),
	('Paige Love', 'Is it free?', 'paige@gmail.com', 'password'::bytea),
	('Eugene Paul', 'The sky is clear; the stars are twinkling.', 'eugene@gmail.com', 'password'::bytea),
	('Kurt Matthews', 'She was too short to see over the fence.', 'kurt@gmail.com', 'password'::bytea),
	('Renaldo Schultz', 'Hurry!', 'renaldo@gmail.com', 'password'::bytea),
	('Keenan Simpson', 'Malls are great places to shop; I can find everything I need under one roof.', 'keenan@gmail.com', 'password'::bytea),
	('Aldo Dyer', 'We need to rent a room for our party.', 'aldo@gmail.com', 'password'::bytea),
	('Deena Schneider', 'Lets all be unique together until we realise we are all the same.', 'deena@gmail.com', 'password'::bytea),
	('Stella Rush', 'Id rather be a bird than a fish.', 'stella@gmail.com', 'password'::bytea),
	('Deirdre Lutz', 'It was getting dark, and we werent there yet.', 'deirdre@gmail.com', 'password'::bytea),
	('Judson Hardin', 'Yeah, I think its a good environment for learning English.', 'judson@gmail.com', 'password'::bytea),
	('Brandon Hobbs', 'Writing a list of random sentences is harder than I initially thought it would be.', 'brandon@gmail.com', 'password'::bytea),
	('Ignacio Holland', 'I was very proud of my nickname throughout high school but today- I couldnt be any different to what my nickname was.', 'ignacio@gmail.com', 'password'::bytea),
	('Shelton Zhang', 'Wednesday is hump day, but has anyone asked the camel if hes happy about it?', 'shelton@gmail.com', 'password'::bytea),
	('Angeline Colon', 'She works two jobs to make ends meet; at least, that was her reason for not having time to join us.', 'angeline@gmail.com', 'password'::bytea),
	('Kermit Whitaker', 'The waves were crashing on the shore; it was a lovely sight.', 'kermit@gmail.com', 'password'::bytea),
	('Jarvis Armstrong', 'They got there early, and they got really good seats.', 'jarvis@gmail.com', 'password'::bytea),
	('Carla Tyler', 'The quick brown fox jumps over the lazy dog.', 'carla@gmail.com', 'password'::bytea),
	('Audrey Mccarty', 'The stranger officiates the meal.', 'audrey@gmail.com', 'password'::bytea),
	('Brendon Henson', 'Sometimes, all you need to do is completely make an ass of yourself and laugh it off to realise that life isnt so bad after all.', 'brendon@gmail.com', 'password'::bytea),
	('Rodney Fuller', 'I love eating toasted cheese and tuna sandwiches.', 'rodney@gmail.com', 'password'::bytea),
	('Esteban Arellano', 'Tom got a small piece of pie.', 'esteban@gmail.com', 'password'::bytea),
	('August Mcfarland', 'Joe made the sugar cookies; Susan decorated them.', 'august@gmail.com', 'password'::bytea),
	('Thurman Parsons', 'Check back tomorrow; I will see if the book has arrived.', 'thurman@gmail.com', 'password'::bytea),
	('Laurel Higgins', 'The body may perhaps compensates for the loss of a true metaphysics.', 'laurel@gmail.com', 'password'::bytea),
	('Mariano Pearson', 'If I dont like something, Ill stay away from it.', 'mariano@gmail.com', 'password'::bytea),
	('Dorian Maldonado', 'I am never at home on Sundays.', 'dorian@gmail.com', 'password'::bytea),
	('Jeannie Green', 'I will never be this young again. Ever. Oh damn I just got older.', 'jeannie@gmail.com', 'password'::bytea),
	('Randy Forbes', 'I really want to go to work, but I am too sick to drive.', 'randy@gmail.com', 'password'::bytea),
	('Thelma Mcdonald', 'Sixty-Four comes asking for bread.', 'thelma@gmail.com', 'password'::bytea),
	('Effie Webb', 'I think I will buy the red car, or I will lease the blue one.', 'effie@gmail.com', 'password'::bytea),
	('Millie Henderson', 'This is the last random sentence I will be writing and I am going to stop mid-sent', 'millie@gmail.com', 'password'::bytea),
	('Malik Everett', 'I want more detailed information.', 'malik@gmail.com', 'password'::bytea),
	('Levi Maddox', 'How was the math test?', 'levi@gmail.com', 'password'::bytea),
	('Ike Day', 'The river stole the gods.', 'ike@gmail.com', 'password'::bytea),
	('Stacy Lindsey', 'Where do random thoughts come from?', 'stacy@gmail.com', 'password'::bytea),
	('Alma Compton', 'She advised him to come back at once.', 'alma@gmail.com', 'password'::bytea),
	('Tory Richardson', 'We have a lot of rain in June.', 'tory@gmail.com', 'password'::bytea),
	('Janell Cox', 'Mary plays the piano.', 'janell@gmail.com', 'password'::bytea),
	('Kathie Stevenson', 'Someone I know recently combined Maple Syrup & buttered Popcorn thinking it would taste like caramel popcorn. It didnt and they dont recommend anyone else do it either.', 'kathie@gmail.com', 'password'::bytea),
	('Darrick Mccoy', 'He said he was not there yesterday; however, many people saw him there.', 'darrick@gmail.com', 'password'::bytea),
	('Taylor Christian', 'I want to buy a onesie but know it wont suit me.', 'taylor@gmail.com', 'password'::bytea),
	('Simone Jenkins', 'Rock music approaches at high velocity.', 'simone@gmail.com', 'password'::bytea),
	('Tracy Diaz', 'There was no ice cream in the freezer, nor did they have money to go to the store.', 'tracy@gmail.com', 'password'::bytea);
