import random

nouns = [
	"guitar",
	"internet",
	"funeral",
	"town",
	"church",
	"guest",
	"effort",
	"chest",
	"hair",
	"personality",
	"departure",
	"awareness",
	"recognition",
	"throat",
	"injury",
	"two",
	"memory",
	"economics",
	"explanation",
	"engineering",
	"problem",
	"indication",
	"communication",
	"storage",
	"association",
	"reading",
	"sister",
	"manager",
	"television",
	"growth",
	"night",
	"inflation",
	"insect",
	"office",
	"tongue",
	"organization",
	"series",
	"article",
	"agency",
	"medicine",
	"patience",
	"piano",
	"map",
	"client",
	"entry",
	"attention",
	"decision",
	"argument",
	"reality",
	"investment",
]

adjectives = [
	"odd",
	"boring",
	"sexual",
	"suitable",
	"confident",
	"technical",
	"conscious",
	"anxious",
	"electrical",
	"similar",
	"aggressive",
	"pregnant",
	"global",
	"lonely",
	"critical",
	"relevant",
	"environmental",
	"remarkable",
	"cultural",
	"pleasant",
	"large",
	"logical",
	"able",
	"unfair",
	"efficient",
	"numerous",
	"scared",
	"suspicious",
	"civil",
	"unusual",
	"responsible",
	"sufficient",
	"every",
	"interesting",
	"mental",
	"wooden",
	"nervous",
	"weak",
	"historical",
	"capable",
	"successfully",
	"sudden",
	"tall",
	"strong",
	"additional",
	"various",
	"federal",
	"careful",
	"decent",
	"distinct",
]

sentences = [
	"He turned in the research paper on Friday; otherwise, he would have not passed the class.",
	"He said he was not there yesterday; however, many people saw him there.",
	"Last Friday in three week’s time I saw a spotted striped blue worm shake hands with a legless lizard.",
	"I think I will buy the red car, or I will lease the blue one.",
	"The memory we used to share is no longer coherent.",
	"Should we start class now, or should we wait for everyone to get here?",
	"I would have gotten the promotion, but my attendance wasn’t good enough.",
	"I am counting my calories, yet I really want dessert.",
	"Is it free?",
	"Abstraction is often one floor above you.",
	"There was no ice cream in the freezer, nor did they have money to go to the store.",
	"I hear that Nancy is very pretty.",
	"Yeah, I think its a good environment for learning English.",
	"She was too short to see over the fence.",
	"We have never been to Asia, nor have we visited Africa.",
	"Lets all be unique together until we realise we are all the same.",
	"Sometimes it is better to just walk away from things and go back to them later when you’re in a better frame of mind.",
	"Sixty-Four comes asking for bread.",
	"I was very proud of my nickname throughout high school but today- I couldn’t be any different to what my nickname was.",
	"If you like tuna and tomato sauce- try combining the two. It’s really not as bad as it sounds.",
	"The sky is clear; the stars are twinkling.",
	"The river stole the gods.",
	"She folded her handkerchief neatly.",
	"This is the last random sentence I will be writing and I am going to stop mid-sent",
	"It was getting dark, and we weren’t there yet.",
	"Wednesday is hump day, but has anyone asked the camel if he’s happy about it?",
	"I am never at home on Sundays.",
	"The mysterious diary records the voice.",
	"Joe made the sugar cookies; Susan decorated them.",
	"This is a Japanese doll.",
	"The stranger officiates the meal.",
	"When I was little I had a car door slammed shut on my hand. I still remember it quite vividly.",
	"A purple pig and a green donkey flew a kite in the middle of the night and ended up sunburnt.",
	"The body may perhaps compensates for the loss of a true metaphysics.",
	"The waves were crashing on the shore; it was a lovely sight.",
	"She did not cheat on the test, for it was not the right thing to do.",
	"She always speaks to him in a loud voice.",
	"She advised him to come back at once.",
	"Where do random thoughts come from?",
	"The clock within this blog and the clock on my laptop are 1 hour different from each other.",
	"Writing a list of random sentences is harder than I initially thought it would be.",
	"The lake is a long way from here.",
	"Mary plays the piano.",
	"I am happy to take your donation; any amount will be greatly appreciated.",
	"The quick brown fox jumps over the lazy dog.",
	"Tom got a small piece of pie.",
	"I want more detailed information.",
	"Let me help you with your baggage.",
	"Sometimes, all you need to do is completely make an ass of yourself and laugh it off to realise that life isn’t so bad after all.",
	"Check back tomorrow; I will see if the book has arrived.",
	"She wrote him a long letter, but he didnt read it.",
	"We have a lot of rain in June.",
	"There were white out conditions in the town; subsequently, the roads were impassable.",
	"Please wait outside of the house.",
	"The old apple revels in its authority.",
	"I really want to go to work, but I am too sick to drive.",
	"How was the math test?",
	"Cats are good pets, for they are clean and are not noisy.",
	"Someone I know recently combined Maple Syrup & buttered Popcorn thinking it would taste like caramel popcorn. It didn’t and they don’t recommend anyone else do it either.",
	"He told us a very exciting adventure story.",
	"Two seats were vacant.",
	"Wow, does that work?",
	"My Mum tries to be cool by saying that she likes all the same things that I do.",
	"Hurry!",
	"A glittering gem is not enough.",
	"She only paints with bold colors; she does not like pastels.",
	"She did her best to help him.",
	"They got there early, and they got really good seats.",
	"I checked to make sure that he was still alive.",
	"Italy is my favorite country; in fact, I plan to spend two weeks there next year.",
	"The book is in front of the table.",
	"We need to rent a room for our party.",
	"If I don’t like something, I’ll stay away from it.",
	"Dont step on the broken glass.",
	"I often see the time 11:11 or 12:34 on clocks.",
	"I love eating toasted cheese and tuna sandwiches.",
	"If Purple People Eaters are real... where do they find purple people to eat?",
	"A song can make or ruin a person’s day if they let it get to them.",
	"She works two jobs to make ends meet; at least, that was her reason for not having time to join us.",
	"I will never be this young again. Ever. Oh damn... I just got older.",
	"Id rather be a bird than a fish.",
	"Everyone was busy, so I went to the movie alone.",
	"The shooter says goodbye to his love.",
	"Malls are great places to shop; I can find everything I need under one roof.",
	"She borrowed the book from him many years ago and hasnt yet returned it.",
	"If the Easter Bunny and the Tooth Fairy had babies would they take your teeth and leave chocolate for you?",
	"Christmas is coming.",
	"Rock music approaches at high velocity.",
	"What was the person thinking when they discovered cow’s milk was fine for human consumption... and why did they do it in the first place!?",
	"I currently have 4 windows open up... and I don’t know why.",
	"He didn’t want to go to the dentist, yet he went anyway.",
	"I want to buy a onesie... but know it won’t suit me.",
	"He ran out of money, so he had to stop playing poker.",
]


projects = []
for user_id in range(1, 50 + 1):
	num_projects = random.randint(1, 5)
	for i in range(num_projects):
		projects.append(f"('{random.choice(adjectives)} {random.choice(nouns)}', '{' '.join(random.sample(sentences, 3))}', {user_id})")

with open('insert-projects.sql', 'w') as f:
	f.write("INSERT into projects (name, description, user_id) values\n")

	f.write(',\n'.join(projects))

	f.write('\n;')
